import type { GetPassiveSkillsResult } from "../../api/passive_skill.js";

export const passiveSkills: GetPassiveSkillsResult = {
    character: 2,
    ascendancy: 2,
    alternate_ascendancy: 13,
    hashes: [
        1461, 2715, 4269, 4481, 5443, 6538, 6797, 6799, 7085, 7488, 7594, 8001,
        8938, 9206, 9469, 12412, 12801, 13375, 14292, 16243, 18182, 18707,
        18769, 18770, 19506, 19858, 20807, 20953, 21033, 21984, 22618, 23334,
        24848, 25058, 26067, 27656, 27879, 28995, 29454, 31039, 31508, 32555,
        32657, 32681, 32763, 33310, 33545, 33903, 33989, 35255, 36221, 36281,
        36287, 36858, 37504, 38662, 38995, 39521, 39861, 41476, 41866, 42104,
        44316, 45035, 45202, 45313, 45436, 45593, 46277, 48099, 48660, 48878,
        49379, 49391, 49605, 49621, 49900, 49978, 50150, 50338, 51146, 51524,
        52031, 52848, 53086, 53114, 53456, 53615, 53828, 54142, 55880, 56295,
        57080, 58302, 59220, 59370, 59606, 59837, 60440, 60735, 60737, 61653,
        61834, 62744, 63194, 63251, 63795, 64028, 64265, 64878, 65210, 65427,
        65502, 65528,
    ],
    hashes_ex: [
        157, 161, 163, 165, 167, 195, 196, 197, 198, 199, 200, 201, 202, 203,
        204, 205, 206,
    ],
    mastery_effects: {
        "44316": 47642,
        "31039": 2987,
        "48660": 17942,
        "32657": 48980,
        "49391": 64511,
        "53828": 42540,
        "7488": 62252,
        "65528": 57074,
        "53615": 61097,
        "58302": 9755,
    },
    skill_overrides: {
        "53615": {
            name: "曲空之符文嵌板",
            icon: "Art/2DArt/SkillIcons/passives/AtlasTrees/RuneGraftingIcon11.png",
            activeEffectImage:
                "Art/2DArt/UIImages/InGame/Village/RuneCraftingPassiveBG.png",
            isMastery: true,
            inactiveIcon:
                "Art/2DArt/SkillIcons/passives/AtlasTrees/RuneGraftingIcon11.png",
            activeIcon:
                "Art/2DArt/SkillIcons/passives/AtlasTrees/RuneGraftingIcon11.png",
            stats: [
                "你受到的有益效果消减速度减慢 30%",
                "你身上的减益效果消失速度加快 30%",
            ],
            reminderText: ["（效果无法低于正常消退速率的 25%）"],
        },
        "59370": {
            name: "雷默科弓手的文身",
            icon: "Art/2DArt/SkillIcons/passives/accuracy.png",
            activeEffectImage:
                "Art/2DArt/UIImages/InGame/AncestralTrial/PassiveTreeTattoos/RamakoTribePassiveBG.png",
            isTattoo: true,
            stats: ["命中值提高 5%"],
        },
    },
    items: [
        {
            verified: false,
            w: 1,
            h: 1,
            icon: "https://poecdn.game.qq.com/gen/image/WzI1LDE0LHsiZiI6IjJESXRlbXMvSmV3ZWxzL05ld0dlbUJhc2UzIiwidyI6MSwiaCI6MSwic2NhbGUiOjEsImZyYWN0dXJlZCI6dHJ1ZX1d/a68dec0dae/NewGemBase3.png",
            league: "S28赛季",
            id: "0b84cadbbf9e8e010ffc3796c808d7bfeb8d96de680837e4e20584107695322b",
            fractured: true,
            name: "末日精华",
            typeLine: "大型星团珠宝",
            baseType: "大型星团珠宝",
            rarity: "Rare",
            ilvl: 85,
            identified: true,
            requirements: [
                {
                    name: "等级",
                    values: [["67", 0]],
                    displayMode: 0,
                    type: 62,
                },
            ],
            enchantMods: [
                "增加 12 个天赋技能",
                "其中 2 个增加的天赋为【珠宝槽】",
                "增加的小天赋获得：法术伤害提高 10%",
            ],
            explicitMods: [
                "添加的小天赋还获得：所有元素抗性 +2%",
                "增加的小天赋还获得：+10 最大生命",
                "增加的小天赋效果提高 35%",
            ],
            fracturedMods: ["增加的小天赋还获得：魔力再生速度加快 6%"],
            descrText:
                "放入天赋树上配置好的大型珠宝槽。增加的天赋跟珠宝范围无关。可以右键点击从插槽中移除。",
            frameType: 2,
            x: 20,
            y: 0,
            inventoryId: "PassiveJewels",
        },
        {
            verified: false,
            w: 1,
            h: 1,
            icon: "https://poecdn.game.qq.com/gen/image/WzI1LDE0LHsiZiI6IjJESXRlbXMvSmV3ZWxzL2Jhc2ljaW50IiwidyI6MSwiaCI6MSwic2NhbGUiOjF9XQ/510013aec2/basicint.png",
            league: "S28赛季",
            id: "dc9a21c5a00dabe36e7319a6c12da6cdb18dc72ccb74612df9aa4230e25334ff",
            name: "灾变之息",
            typeLine: "钴蓝珠宝",
            baseType: "钴蓝珠宝",
            rarity: "Rare",
            ilvl: 83,
            identified: true,
            explicitMods: [
                "法术伤害提高 10%",
                "法术伤害在持盾牌时提高 15%",
                "攻击速度加快 3%",
                "生命上限提高 6%",
            ],
            descrText:
                "放置到一个天赋树的珠宝插槽中以产生效果。右键点击以移出插槽。",
            frameType: 2,
            x: 47,
            y: 0,
            inventoryId: "PassiveJewels",
        },
        {
            verified: false,
            w: 1,
            h: 1,
            icon: "https://poecdn.game.qq.com/gen/image/WzI1LDE0LHsiZiI6IjJESXRlbXMvSmV3ZWxzL1NlYXJjaGluZ0V5ZSIsInciOjEsImgiOjEsInNjYWxlIjoxLCJmcmFjdHVyZWQiOnRydWV9XQ/bb79747f8e/SearchingEye.png",
            league: "S28赛季",
            id: "e7feada160da8310644e18fbb6679980790e27bdcddb4673378089b7bd18bb4a",
            abyssJewel: true,
            fractured: true,
            name: "咒缚的棱镜",
            typeLine: "锐利之凝珠宝",
            baseType: "锐利之凝珠宝",
            rarity: "Rare",
            ilvl: 83,
            identified: true,
            properties: [
                {
                    name: "深渊",
                    values: [],
                    displayMode: 0,
                },
            ],
            requirements: [
                {
                    name: "等级",
                    values: [["65", 0]],
                    displayMode: 0,
                    type: 62,
                },
            ],
            explicitMods: [
                "攻击附加 12 - 22 基础火焰伤害",
                "攻击附加 4 - 46 基础闪电伤害",
                "法杖攻击附加 3 到 42 点闪电伤害",
            ],
            fracturedMods: ["+40 最大生命"],
            descrText:
                "放入一个物品的深渊插槽或天赋树上的珠宝插槽中以生效。右键点击以移出插槽。",
            frameType: 2,
            x: 45,
            y: 0,
            inventoryId: "PassiveJewels",
        },
        {
            verified: false,
            w: 1,
            h: 1,
            icon: "https://poecdn.game.qq.com/gen/image/WzI1LDE0LHsiZiI6IjJESXRlbXMvSmV3ZWxzL1VubmF0dXJhbEluc3RpbmN0IiwidyI6MSwiaCI6MSwic2NhbGUiOjF9XQ/c37fa5c2b6/UnnaturalInstinct.png",
            league: "S28赛季",
            id: "4fccd02037423c3ba76c582dca58cf768c8fda658d0fdd14081b3ec3a77ec2d8",
            name: "超自然本能",
            typeLine: "翠绿珠宝",
            baseType: "翠绿珠宝",
            rarity: "Unique",
            ilvl: 83,
            identified: true,
            properties: [
                {
                    name: "仅限",
                    values: [["1", 0]],
                    displayMode: 0,
                },
                {
                    name: "范围",
                    values: [["小", 0]],
                    displayMode: 0,
                    type: 24,
                },
            ],
            explicitMods: [
                "范围内配置的小天赋点技能不会提供任何加成",
                "范围内未配置的小天赋点技能会提供任何加成",
            ],
            descrText:
                "放置到一个天赋树的珠宝插槽中以产生效果。右键点击以移出插槽。",
            flavourText: ["“我不知道我是如何知道的， \r", "但我就是知道。”"],
            frameType: 3,
            x: 5,
            y: 0,
            inventoryId: "PassiveJewels",
        },
        {
            verified: false,
            w: 1,
            h: 1,
            icon: "https://poecdn.game.qq.com/gen/image/WzI1LDE0LHsiZiI6IjJESXRlbXMvSmV3ZWxzL1NlYXJjaGluZ0V5ZSIsInciOjEsImgiOjEsInNjYWxlIjoxLCJmcmFjdHVyZWQiOnRydWV9XQ/bb79747f8e/SearchingEye.png",
            league: "S28赛季",
            id: "fa7514fc1f4dbcd7cec831c54261f3c381f3112ccceb814758459a8c9b1d0aee",
            abyssJewel: true,
            fractured: true,
            name: "空洞 眩光",
            typeLine: "锐利之凝珠宝",
            baseType: "锐利之凝珠宝",
            rarity: "Rare",
            ilvl: 83,
            identified: true,
            properties: [
                {
                    name: "深渊",
                    values: [],
                    displayMode: 0,
                },
            ],
            requirements: [
                {
                    name: "等级",
                    values: [["65", 0]],
                    displayMode: 0,
                    type: 62,
                },
            ],
            explicitMods: [
                "攻击附加 15 - 26 基础火焰伤害",
                "攻击附加 8 - 17 基础冰霜伤害",
                "法杖攻击附加 4 到 49 点闪电伤害",
            ],
            fracturedMods: ["+40 最大生命"],
            descrText:
                "放入一个物品的深渊插槽或天赋树上的珠宝插槽中以生效。右键点击以移出插槽。",
            frameType: 2,
            x: 4,
            y: 0,
            inventoryId: "PassiveJewels",
        },
        {
            verified: false,
            w: 1,
            h: 1,
            icon: "https://poecdn.game.qq.com/gen/image/WzI1LDE0LHsiZiI6IjJESXRlbXMvSmV3ZWxzL0Nvbm5lY3RlZEpld2VsIiwidyI6MSwiaCI6MSwic2NhbGUiOjF9XQ/1d2c1f698a/ConnectedJewel.png",
            league: "S28赛季",
            id: "3f93b990bd06d817adf551849990b99d2b8104cdd27e8f7df05644688d52cd6e",
            name: "希望之线",
            typeLine: "赤红珠宝",
            baseType: "赤红珠宝",
            rarity: "Unique",
            ilvl: 87,
            identified: true,
            properties: [
                {
                    name: "范围",
                    values: [["变量", 1]],
                    displayMode: 0,
                    type: 24,
                },
            ],
            explicitMods: [
                "只影响巨型圈内的天赋",
                "范围内的天赋技能无需连接到你的天赋树即可配置\n所有元素抗性 +-15%\n通途",
            ],
            descrText:
                "放置到一个天赋树的珠宝插槽中以产生效果。右键点击以移出插槽。",
            flavourText: [
                "我们触碰不到彼此，其中一人思索，其中一人憧憬，就这样在黑暗中百年飞逝。",
            ],
            frameType: 3,
            x: 2,
            y: 0,
            inventoryId: "PassiveJewels",
        },
        {
            verified: false,
            w: 1,
            h: 1,
            icon: "https://poecdn.game.qq.com/gen/image/WzI1LDE0LHsiZiI6IjJESXRlbXMvSmV3ZWxzL05ld0dlbUJhc2UzIiwidyI6MSwiaCI6MSwic2NhbGUiOjF9XQ/db35e60885/NewGemBase3.png",
            league: "S28赛季",
            id: "53559dc6d251e5a1d8dd4e1ef6f8488b1e71be56e0889aae169ba2aa62f79200",
            name: "鹰翼光芒",
            typeLine: "大型星团珠宝",
            baseType: "大型星团珠宝",
            rarity: "Rare",
            ilvl: 83,
            identified: true,
            requirements: [
                {
                    name: "等级",
                    values: [["54", 0]],
                    displayMode: 0,
                    type: 62,
                },
            ],
            enchantMods: [
                "增加 8 个天赋技能",
                "其中 2 个增加的天赋为【珠宝槽】",
                "增加的小天赋获得：闪电伤害提高 12%",
            ],
            explicitMods: [
                "增加的小天赋还获得：+3 所有属性",
                "其中 1 个增加的天赋为【多利亚尼之训】",
                "其中 1 个增加的天赋为【棱光之心】",
                "其中 1 个增加的天赋为【风暴痛饮】",
            ],
            descrText:
                "放入天赋树上配置好的大型珠宝槽。增加的天赋跟珠宝范围无关。可以右键点击从插槽中移除。",
            frameType: 2,
            x: 17,
            y: 0,
            inventoryId: "PassiveJewels",
        },
        {
            verified: false,
            w: 1,
            h: 1,
            icon: "https://poecdn.game.qq.com/gen/image/WzI1LDE0LHsiZiI6IjJESXRlbXMvSmV3ZWxzL1ByaXN0aW5lQ29uZGl0aW9uaW5nIiwidyI6MSwiaCI6MSwic2NhbGUiOjF9XQ/5ad58d3a2e/PristineConditioning.png",
            league: "S28赛季",
            id: "ed28f4f34fed8c1f2910644cd1362f256d496abd91c80f06f50b030dc9f41f0f",
            name: "先祖的远视",
            typeLine: "翠绿珠宝",
            baseType: "翠绿珠宝",
            rarity: "Unique",
            ilvl: 86,
            identified: true,
            properties: [
                {
                    name: "仅限",
                    values: [["1", 0]],
                    displayMode: 0,
                },
            ],
            explicitMods: [
                "+9 敏捷",
                "法术压制几率词缀有 50% 也套用于避免元素异常状态几率",
            ],
            descrText:
                "放置到一个天赋树的珠宝插槽中以产生效果。右键点击以移出插槽。",
            flavourText: [
                "祖先的灵魂指引我们\r",
                "从群岛来到大陆。\r",
                "我们纯洁的灵魂与先祖别深深相连。",
            ],
            frameType: 3,
            x: 53,
            y: 0,
            inventoryId: "PassiveJewels",
        },
        {
            verified: false,
            w: 1,
            h: 1,
            icon: "https://poecdn.game.qq.com/gen/image/WzI1LDE0LHsiZiI6IjJESXRlbXMvSmV3ZWxzL0VsZGVySmV3ZWwiLCJ3IjoxLCJoIjoxLCJzY2FsZSI6MX1d/278c673716/ElderJewel.png",
            league: "S28赛季",
            id: "8b480bda02cba3e0a4a6eb30c8605328ac5de7d5cfdc4794391dd2f08d5c689c",
            name: "守望之眼",
            typeLine: "三相珠宝",
            baseType: "三相珠宝",
            rarity: "Unique",
            ilvl: 87,
            identified: true,
            properties: [
                {
                    name: "仅限",
                    values: [["1", 0]],
                    displayMode: 0,
                },
            ],
            explicitMods: [
                "能量护盾上限提高 5%",
                "生命上限提高 6%",
                "魔力上限提高 4%",
                "受到【精准】影响时，+24% 暴击伤害加成",
                "受到【活力】影响时，药剂的生命回复提高 62%",
                "受到【迅捷】影响时获得【迷踪】状态",
            ],
            descrText:
                "放置到一个天赋树的珠宝插槽中以产生效果。右键点击以移出插槽。",
            flavourText: [
                "他们一个又一个地挺身而出，\r",
                "与他们无从理解更无从对抗的怪物战斗，\r",
                "然后前赴后继地成为怪物的一份子。",
            ],
            frameType: 3,
            x: 51,
            y: 0,
            inventoryId: "PassiveJewels",
        },
    ],
    jewel_data: {
        "20": {
            type: "JewelPassiveTreeExpansionLarge",
            subgraph: {
                groups: {
                    expansion_20: {
                        proxy: "18756",
                        nodes: [
                            "1195",
                            "195",
                            "196",
                            "197",
                            "198",
                            "199",
                            "200",
                            "201",
                            "202",
                            "203",
                            "204",
                            "205",
                            "206",
                        ],
                        x: 4887.73,
                        y: -8158.76,
                        orbits: [3],
                    },
                },
                nodes: {
                    "1195": {
                        skill: "21841",
                        name: "法术伤害专精",
                        icon: "Art/2DArt/SkillIcons/passives/AltMasteryGroupCast.png",
                        isMastery: true,
                        stats: [],
                        group: "expansion_20",
                        orbit: 0,
                        orbitIndex: 0,
                        out: [],
                        in: [],
                    },
                    "195": {
                        skill: "21845",
                        name: "法术伤害",
                        icon: "Art/2DArt/SkillIcons/passives/IncreasedSpellDamageNode.png",
                        stats: [
                            "法术伤害提高 13%",
                            "+13 最大生命",
                            "魔力再生速度提高 8%",
                            "+2% 所有元素抗性",
                        ],
                        group: "expansion_20",
                        orbit: 3,
                        orbitIndex: 0,
                        out: ["196"],
                        in: ["206"],
                    },
                    "196": {
                        skill: "21845",
                        name: "法术伤害",
                        icon: "Art/2DArt/SkillIcons/passives/IncreasedSpellDamageNode.png",
                        stats: [
                            "法术伤害提高 13%",
                            "+13 最大生命",
                            "魔力再生速度提高 8%",
                            "+2% 所有元素抗性",
                        ],
                        group: "expansion_20",
                        orbit: 3,
                        orbitIndex: 1,
                        out: ["197"],
                        in: ["195"],
                    },
                    "197": {
                        skill: "21845",
                        name: "法术伤害",
                        icon: "Art/2DArt/SkillIcons/passives/IncreasedSpellDamageNode.png",
                        stats: [
                            "法术伤害提高 13%",
                            "+13 最大生命",
                            "魔力再生速度提高 8%",
                            "+2% 所有元素抗性",
                        ],
                        group: "expansion_20",
                        orbit: 3,
                        orbitIndex: 3,
                        out: ["198"],
                        in: ["196"],
                    },
                    "198": {
                        skill: "13170",
                        name: "中型珠宝槽",
                        icon: "Art/2DArt/SkillIcons/passives/MasteryBlank.png",
                        isJewelSocket: true,
                        expansionJewel: {
                            size: 1,
                            index: 2,
                            proxy: "24452",
                            parent: "21984",
                        },
                        stats: [],
                        group: "expansion_20",
                        orbit: 3,
                        orbitIndex: 4,
                        out: ["199"],
                        in: ["197"],
                    },
                    "199": {
                        skill: "21845",
                        name: "法术伤害",
                        icon: "Art/2DArt/SkillIcons/passives/IncreasedSpellDamageNode.png",
                        stats: [
                            "法术伤害提高 13%",
                            "+13 最大生命",
                            "魔力再生速度提高 8%",
                            "+2% 所有元素抗性",
                        ],
                        group: "expansion_20",
                        orbit: 3,
                        orbitIndex: 5,
                        out: ["200"],
                        in: ["198"],
                    },
                    "200": {
                        skill: "21845",
                        name: "法术伤害",
                        icon: "Art/2DArt/SkillIcons/passives/IncreasedSpellDamageNode.png",
                        stats: [
                            "法术伤害提高 13%",
                            "+13 最大生命",
                            "魔力再生速度提高 8%",
                            "+2% 所有元素抗性",
                        ],
                        group: "expansion_20",
                        orbit: 3,
                        orbitIndex: 7,
                        out: ["201"],
                        in: ["199"],
                    },
                    "201": {
                        skill: "21845",
                        name: "法术伤害",
                        icon: "Art/2DArt/SkillIcons/passives/IncreasedSpellDamageNode.png",
                        stats: [
                            "法术伤害提高 13%",
                            "+13 最大生命",
                            "魔力再生速度提高 8%",
                            "+2% 所有元素抗性",
                        ],
                        group: "expansion_20",
                        orbit: 3,
                        orbitIndex: 8,
                        out: ["202"],
                        in: ["200"],
                    },
                    "202": {
                        skill: "21845",
                        name: "法术伤害",
                        icon: "Art/2DArt/SkillIcons/passives/IncreasedSpellDamageNode.png",
                        stats: [
                            "法术伤害提高 13%",
                            "+13 最大生命",
                            "魔力再生速度提高 8%",
                            "+2% 所有元素抗性",
                        ],
                        group: "expansion_20",
                        orbit: 3,
                        orbitIndex: 9,
                        out: ["203", "201"],
                        in: ["21984"],
                    },
                    "203": {
                        skill: "21845",
                        name: "法术伤害",
                        icon: "Art/2DArt/SkillIcons/passives/IncreasedSpellDamageNode.png",
                        stats: [
                            "法术伤害提高 13%",
                            "+13 最大生命",
                            "魔力再生速度提高 8%",
                            "+2% 所有元素抗性",
                        ],
                        group: "expansion_20",
                        orbit: 3,
                        orbitIndex: 11,
                        out: ["204"],
                        in: ["202"],
                    },
                    "204": {
                        skill: "21845",
                        name: "法术伤害",
                        icon: "Art/2DArt/SkillIcons/passives/IncreasedSpellDamageNode.png",
                        stats: [
                            "法术伤害提高 13%",
                            "+13 最大生命",
                            "魔力再生速度提高 8%",
                            "+2% 所有元素抗性",
                        ],
                        group: "expansion_20",
                        orbit: 3,
                        orbitIndex: 12,
                        out: ["205"],
                        in: ["203"],
                    },
                    "205": {
                        skill: "21845",
                        name: "法术伤害",
                        icon: "Art/2DArt/SkillIcons/passives/IncreasedSpellDamageNode.png",
                        stats: [
                            "法术伤害提高 13%",
                            "+13 最大生命",
                            "魔力再生速度提高 8%",
                            "+2% 所有元素抗性",
                        ],
                        group: "expansion_20",
                        orbit: 3,
                        orbitIndex: 13,
                        out: ["206"],
                        in: ["204"],
                    },
                    "206": {
                        skill: "64583",
                        name: "中型珠宝槽",
                        icon: "Art/2DArt/SkillIcons/passives/MasteryBlank.png",
                        isJewelSocket: true,
                        expansionJewel: {
                            size: 1,
                            index: 0,
                            proxy: "58194",
                            parent: "21984",
                        },
                        stats: [],
                        group: "expansion_20",
                        orbit: 3,
                        orbitIndex: 15,
                        out: ["195"],
                        in: ["205"],
                    },
                },
            },
        },
        "47": {
            type: "JewelInt",
        },
        "45": {
            type: "JewelAbyssRanged",
        },
        "5": {
            type: "JewelDex",
            radius: 960,
        },
        "4": {
            type: "JewelAbyssRanged",
        },
        "2": {
            type: "JewelStr",
            radius: 2880,
            radiusMin: 2400,
        },
        "17": {
            type: "JewelPassiveTreeExpansionLarge",
            subgraph: {
                groups: {
                    expansion_17: {
                        proxy: "48132",
                        nodes: [
                            "1156",
                            "157",
                            "158",
                            "159",
                            "160",
                            "161",
                            "163",
                            "165",
                            "167",
                        ],
                        x: 8807.45,
                        y: 129.815,
                        orbits: [3],
                    },
                },
                nodes: {
                    "1156": {
                        skill: "15015",
                        name: "闪电伤害专精",
                        icon: "Art/2DArt/SkillIcons/passives/AltMasteryGroupLightning.png",
                        isMastery: true,
                        stats: [],
                        group: "expansion_17",
                        orbit: 0,
                        orbitIndex: 0,
                        out: [],
                        in: [],
                    },
                    "157": {
                        skill: "6910",
                        name: "中型珠宝槽",
                        icon: "Art/2DArt/SkillIcons/passives/MasteryBlank.png",
                        isJewelSocket: true,
                        expansionJewel: {
                            size: 1,
                            index: 0,
                            proxy: "35926",
                            parent: "32763",
                        },
                        stats: [],
                        group: "expansion_17",
                        orbit: 3,
                        orbitIndex: 1,
                        out: ["158"],
                        in: ["167"],
                    },
                    "158": {
                        skill: "49817",
                        name: "闪电伤害",
                        icon: "Art/2DArt/SkillIcons/passives/LightningDamagenode.png",
                        stats: ["+3 全属性", "闪电伤害提高 12%"],
                        group: "expansion_17",
                        orbit: 3,
                        orbitIndex: 3,
                        out: ["159"],
                        in: ["157"],
                    },
                    "159": {
                        skill: "17050",
                        name: "棱光之心",
                        icon: "Art/2DArt/SkillIcons/passives/IncreasedElementalDamage.png",
                        isNotable: true,
                        stats: ["+10% 所有元素抗性", "元素伤害提高 30%"],
                        group: "expansion_17",
                        orbit: 3,
                        orbitIndex: 4,
                        out: ["160"],
                        in: ["158"],
                    },
                    "160": {
                        skill: "49817",
                        name: "闪电伤害",
                        icon: "Art/2DArt/SkillIcons/passives/LightningDamagenode.png",
                        stats: ["+3 全属性", "闪电伤害提高 12%"],
                        group: "expansion_17",
                        orbit: 3,
                        orbitIndex: 5,
                        out: ["161"],
                        in: ["159"],
                    },
                    "161": {
                        skill: "33753",
                        name: "中型珠宝槽",
                        icon: "Art/2DArt/SkillIcons/passives/MasteryBlank.png",
                        isJewelSocket: true,
                        expansionJewel: {
                            size: 1,
                            index: 2,
                            proxy: "50179",
                            parent: "32763",
                        },
                        stats: [],
                        group: "expansion_17",
                        orbit: 3,
                        orbitIndex: 7,
                        out: ["163"],
                        in: ["160"],
                    },
                    "163": {
                        skill: "22607",
                        name: "风暴痛饮",
                        icon: "Art/2DArt/SkillIcons/passives/IncreasedLightningDamage.png",
                        isNotable: true,
                        stats: [
                            "伤害穿透 8% 的闪电抗性",
                            "闪电伤害的 0.5% 转化为能量护盾偷取",
                        ],
                        reminderText: [
                            "（被偷取的能量护盾会持续恢复。可以同时进行多次偷取，次数有上限）",
                        ],
                        group: "expansion_17",
                        orbit: 3,
                        orbitIndex: 9,
                        out: ["165"],
                        in: ["161"],
                    },
                    "165": {
                        skill: "49817",
                        name: "闪电伤害",
                        icon: "Art/2DArt/SkillIcons/passives/LightningDamagenode.png",
                        stats: ["+3 全属性", "闪电伤害提高 12%"],
                        group: "expansion_17",
                        orbit: 3,
                        orbitIndex: 12,
                        out: ["167", "163"],
                        in: ["32763"],
                    },
                    "167": {
                        skill: "7039",
                        name: "多里亚尼之训",
                        icon: "Art/2DArt/SkillIcons/passives/IncreasedElementalDamage.png",
                        isNotable: true,
                        stats: [
                            "元素伤害的 0.2% 转化为生命偷取",
                            "元素伤害提高 25%",
                        ],
                        reminderText: [
                            "(吸取的生命会随时间逐渐回复。多个吸取效果可以同时发生, 但有一个上限)",
                        ],
                        group: "expansion_17",
                        orbit: 3,
                        orbitIndex: 15,
                        out: ["157"],
                        in: ["165"],
                    },
                },
            },
        },
        "53": {
            type: "JewelDex",
        },
        "51": {
            type: "JewelPrismatic",
        },
    },
};
